swagger: "2.0"
info:
    title: Argent Bank Transaction API
    description: API model proposal for user transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Retrieve transactions
      description: Get all transactions datas for the current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/GetAllTransactions"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transactions not found
        "500":
          description: Internal Server Error
  /user/transactions/{id}:
      get:
          security:
            - Bearer: []
          tags:
            - Transaction module
          summary: Retrieve a specific transaction
          description: Get transaction by an ID
          parameters:
            - in: header
              name: Authorization
              description: Attach Bearer JWT token
              required: true
              type: string
            - in: path
              name: id
              description: ID of the transaction to retrieve
              required: true
              type: string
          produces:
            - application/json
          responses:
            "200":
              description: Transaction retrieved successfully
              schema:
                $ref: "#/definitions/GetTransactionById"
            "400":
              description: Invalid Fields
            "401":
              description: Unauthorized
            "404":
              description: Transaction not found
            "500":
              description: Internal Server Error
      patch:
          security:
              - Bearer: []
          tags:
              - Transaction module
          summary: Edit transaction information
          description: API for updating a transaction
          parameters:
              - in: header
                name: Authorization
                description: Attach Bearer JWT token
                required: true
                type: string
              - in: path
                name: id
                description: Id of the transaction that needs to be edited
                required: true
                type: string
              - in: body
                name: body
                description: Edit transaction
                required: true
                schema:
                    $ref: "#/definitions/ApiTransactionPatch"
          produces:
              - application/json
          responses:
              "200":
                  description: Transaction edited successfully
                  schema:
                      $ref: "#/definitions/ApiTransactionPatchUpdated"
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transaction not found
              "500":
                  description: Internal Server Error
      delete:
          security:
              - Bearer: []
          tags:
              - Transaction module
          summary: Delete API information
          description: API for deleting transaction information
          parameters:
              - in: header
                name: Authorization
                description: Attach Bearer JWT token
                required: true
                type: string
              - in: path
                name: id
                description: Id of the transaction that needs to be deleted
                required: true
                type: string
              - in: body
                name: delete
                description: Delete information
                required: true
                schema:
                    $ref: "#/definitions/ApiInformationDelete"
          produces:
              - application/json
          responses:
              "200":
                  description: Information delete
                  schema:
                    $ref: "#/definitions/DeleteConfirmation"
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transaction not found
              "500":
                  description: Internal Server Error
securityDefinitions:
  Bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  GetAllTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  GetTransactionById:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'
  ApiTransactionPatchUpdated:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Id of the transaction
      date:
        type: string
        description: Date of the transaction
      amount:
        type: number
        description: Amount of the transaction
      description:
        type: string
        description: Description of the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes of the transaction     
  ApiTransactionPatch:
   properties:
            category:
              type: string
            notes:
              type: string 
  ApiInformationDelete:
    properties:
      category:
        type: string
      notes:
        type: string
  DeleteConfirmation:
    type: object
    properties:
      status:
        type: string
      message:
        type: string