swagger: "2.0"
info:
    title: Argent Bank Transaction API
    description: API model proposal for user transactions
    version: 2.0.0
    termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v2
schemes:
    - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction module
      summary: Get accountID
      description: API to retrieve accountID
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Unauthorized
        "404":
          description: Transactions not found
        "500":
          description: Internal Server Error
  /user/transactions/{accountID}:
      get:
        security:
            - Bearer: []
        tags:
            - Transaction module
        summary: All transactions Current Month API
        description: Get all data from API with month
        parameters:
          - in: path
            name: accountID
            description: Id of the transaction that needs to be edited
            required: true
            type: string

        produces:
            - application/json
        responses:
            "200":
                description: User transactions retrieved successfully
                schema:
                    $ref: "#/definitions/allTransactionsResponse"
            "400":
                description: Invalid Fields
            "401":
                description: Unauthorized
            "404":
                description: Transactions not found
            "500":
                description: Internal Server Error
  /user/transactions/accountID/{transactionID}:              
      patch:
          security:
              - Bearer: []
          tags:
              - Transaction module
          summary: Transaction Edit API
          description: API for updating a transaction
          parameters:
              - in: header
                name: Authorization
                description: Attach Bearer JWT token
                required: true
                type: string
              - in: path
                name: transactionID
                description: Id of the transaction that needs to be edited
                required: true
                type: string
              - in: body
                name: body
                description: Edit transaction
                required: true
                schema:
                    $ref: "#/definitions/editTransaction"
          produces:
              - application/json
          responses:
              "200":
                  description: Transaction edited successfully
                  schema:
                      $ref: "#/definitions/ApiTransactionResponse"
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transaction not found
              "500":
                  description: Internal Server Error
      delete:
          security:
              - Bearer: []
          tags:
              - Transaction module
          summary: Transaction Delete API
          description: API for deleting a transaction
          parameters:
              - in: header
                name: Authorization
                description: Attach Bearer JWT token
                required: true
                type: string
              - in: path
                name: transactionID
                description: Id of the transaction that needs to be deleted
                required: true
                type: string
          produces:
              - application/json
          responses:
              "200":
                  description: Transaction deleted successfully
              "400":
                  description: Invalid Fields
              "401":
                  description: Unauthorized
              "404":
                  description: Transaction not found
              "500":
                  description: Internal Server Error
securityDefinitions:
  Bearer:
      type: apiKey
      name: Authorization
      in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionsResponse:
        type: object
        properties:
          accountID:
            type: string
          balanceAccount:
            type: number
  allTransactionsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      transactions_1:
        type: array
        items:
          $ref: '#/definitions/Transaction'
      transactions_2:
        type: array
        items:
          $ref: '#/definitions/Transaction'
      transactions_3:
        type: array
        items:
          $ref: '#/definitions/Transaction'

  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: Id of the transaction
      date:
        type: string
        description: Date of the transaction
      amount:
        type: number
        description: Amount of the transaction
      description:
        type: string
        description: Description of the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes of the transaction       
                    
  editTransaction:
        properties:
            category:
                type: string
                description: New category of this transaction
            notes:
                type: string
                description: New notes of this transaction
  ApiTransactionResponse:
        properties:
            category:
              type: string
            notes:
              type: string